highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://sbidari.github.io
author: Subekshya Bidari

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Subekshya Bidari's CV
name: Subekshya Bidari
email: subekshya.bidari@gmail.com
email_full: mailto:subekshya.bidari@gmail
website: sbidari.github.io
website_full: https://sbidari.github.io
github: sbidari
twitter: BidariSubekshya
tel:
tel_full:
google_maps:
address:
  street:
  postcode:
  city: Edinburgh
  state: Colorado
  country: US
google_analytics:

# needed for travis-ci build
exclude: [vendor]
